{
 "title": "Application Overview",
 "tags": [
  "application",
  "spring-boot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Startup Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_milliseconds{service_name=\"demo\"}"
    }
   ]
  },
  {
   "title": "Ready Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_milliseconds{service_name=\"demo\"}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{service_name=\"demo\"}"
    }
   ]
  },
  {
   "title": "System CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{service_name=\"demo\"}"
    }
   ]
  },
  { "title": "Disk & Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "disk_free_bytes{service_name=\"demo\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "disk_total_bytes{service_name=\"demo\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Log Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{service_name=\"demo\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Hello Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hello_count_total{service_name=\"demo\"}"
    }
   ]
  },
  {
   "title": "Hello Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(hello_cost_milliseconds_sum{service_name=\"demo\"}[5m]) / rate(hello_cost_milliseconds_count{service_name=\"demo\"}[5m])",
     "legendFormat": "hello avg cost"
    }
   ]
  }
 ]
}