spring:
  application:
    name: demo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/native-app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 20s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0
